### ISSUE TITLE
Driver class 'org.mariadb.jdbc.Driver' not found Driver files are not downloaded

### ISSUE THREAD

**Issue by rfay** [php-perfect/ddev-intellij-plugin#49] opened 2022-05-14 21:00 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you sure that this bug is related to this DDEV Integration Plugin?

- [X] I am sure

### Describe the bug

It won't surprise me if this isn't actually a bug, but it looks a little scary. I started up the plugin and saw this warning:

![image](https://user-images.githubusercontent.com/112444/168447927-b87d8ad0-c666-4bf7-97b8-326569a17696.png)

(I went ahead and clicked the download link, and so far seems OK, but it looked like something perhaps the plugin should have arranged, not sure.)

### Steps to reproduce

Install for the first time.

### Additional context

Win11 Pro, PhpStorm 2022.1.1, WSL2

**Comment by nico-loeber** [comment] 2022-05-14 21:15
Thanks for reporting this @rfay!

This is indeed the expected behavior, at least the first warning. "DDEV" is just the name of the data source and PHPStorm will inform you, that you need to download those driver files. The plugin does only configure the data source, everything else is handled by intellij itself.
Indeed the 2nd message could be avoided. The plugin will automatically trigger a schema update, so you have auto completion for table names and columns when writing sql statements. This triggers this error as there was no database driver downloaded yet.
I will take a look if I can prevent the automatic schema update if the driver files are not downloaded yet.

**Comment by nico-loeber** [comment] 2022-05-14 21:16
I would like to note that this will only occur if you did never connect to any mariadb database before.

**Comment by nico-loeber** [comment] 2022-06-16 23:22
As already explained, the warning about the missing driver files is the intended behavior as you have to manually confirm to download external files (The driver files). The error in your screenshot does only appear in the notification list and should not pop up as a notification. It is triggert internally when trying to open the database connection if there are no driver files available.
If the plugin would not trigger this error the IDE would not offer you to donwload the files.

For now this is a "won't fix".

**Closed by nico-loeber** 2022-06-16 23:22 UTC
Labels: bug
