### ISSUE TITLE
Version 1.2.3 incompatible with PHPStorm 2024.2

### ISSUE THREAD

**Issue by wp4nuv** [php-perfect/ddev-intellij-plugin#357] opened 2024-08-22 16:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you sure that this bug is related to this DDEV Integration Plugin?

- [X] I am sure

### Describe the bug

On upgrade to version 2024.2, PHPStorm indicates this plugin is not compatible. 

### Additional context

![image](https://github.com/user-attachments/assets/00d994a9-b94c-4929-8f7c-a9d62785a28f)

**Comment by stasadev** [comment] 2024-08-22 16:47
Duplicate of

- #347

**Closed** 2024-08-22 16:48 UTC
Labels: bug
