### ISSUE TITLE
Database connection uses wrong type

### ISSUE THREAD

**Issue by verdure-peuser** [php-perfect/ddev-intellij-plugin#115] opened 2022-10-20 08:12 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you sure that this bug is related to this DDEV Integration Plugin?

- [X] I am sure

### Describe the bug

On projects with mariadb instead of mysql the plugin generates the following connection string

jdbc:mysql://127.0.0.1:49153/db?user=db&password=db

The driver is selected correctly, but the connection via url is using mysql.
If use the following connection string and replace mysql with 'mariadb' it works

jdbc:mariadb://127.0.0.1:49153/db?user=db&password=db

### Steps to reproduce

1. Create DDEV Project with MariaDB
`database:
  type: mariadb
  version: "10.4"`
2. Open project into PHPStorm
3. Start ddev
4. DDEV Integration says running, but db connection fails. ddev describe shows the correct port/user/password is used
5. PHPStorm database connection is type mariadb but connection string contains mysql

![image](https://user-images.githubusercontent.com/7240698/196893664-7d6cf80d-432b-4226-8423-296f6c3d9c95.png)

### Additional context

Ubuntu 20.04
DDEV v.1.21.1
PHPStorm 2022.2.3
DDEV Integration 1.0.1

**Comment by verdure-peuser** [comment] 2022-10-20 08:15
It seems this has been raised before in https://github.com/php-perfect/ddev-intellij-plugin/issues/106 but should be fixed.

**Comment by verdure-peuser** [comment] 2022-10-21 13:14
@nico-loeber understood, sorry for reopening this bug. i could see it in closed but haven't checked against the next release.
If you could mark this with the next milestone for 1.1 it would be visible and hopefully someone else doesn't mention it a 3rd time :)

P.S. i noticed that if you change the type to mariadb, this will only last until you reopen the affected project. The plugin does constantly reset the wrong type after reopening the project.

Thanks for your efforts.

**Comment by nico-loeber** [comment] 2022-10-21 13:24
@verdure-peuser, no problem, it was my mistake to close the issue before releasing the fix.

Yes, all automatically configured settings get updated automatically whenever a change to the ddev container could happen (start/restart). As your manual configuration change is seen as a "mistake" it will is corrected by the plugin.
You can avoid this by adding your own data source with another name (not DDEV).
PHP storm will try to connect all configured data sources, so you will probably still get an error message but you can work with auto completion for SQL queries and all the other stuff.

As I already said, I will try to release the fix asap.

**Comment by nico-loeber** [comment] 2022-11-04 13:02
@verdure-peuser, could you please confirm the issue is solved for you with version 1.0.3 of the plugin?

**Comment by verdure-peuser** [comment] 2022-11-04 13:20
@nico-loeber works like a charm, thanks :)

**Closed** 2022-11-04 13:21 UTC
Labels: bug

**Comment by jonaseberle** [comment] 2022-12-05 16:09
coming from https://github.com/php-perfect/ddev-intellij-plugin/issues/114

@nico-loeber my bad, I thought I was using 1.0.3 but while looking at it today, I have only been offered to upgrade to 1.0.3...
Sorry. Yes, it is working fine with `mariadb`. Thank you!
