### ISSUE TITLE
DDEV intetration entered unkonwn state

### ISSUE THREAD

**Issue by BenediktS1** [php-perfect/ddev-intellij-plugin#209] opened 2023-07-24 19:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you sure that this bug is related to this DDEV Integration Plugin?

- [ ] I am sure

### Describe the bug

PhpStorm 2023.1.4 Message:

DDEV intetration entered unkonwn state
The DDEV Integration Plugin has lost track of the DDEV status. This most likely occurs together with another related error message. Please report this issue if it occurs repeatedly.

### Steps to reproduce

1. Use PhpStorm 2023.1.4, DDEV Plugin 1.1.0 and ddev v1.21.6
2. Edit files
3. PHPStorm shows this message, after some time:

DDEV intetration entered unkonwn state
The DDEV Integration Plugin has lost track of the DDEV status. This most likely occurs together with another related error message. Please report this issue if it occurs repeatedly.

From the options "Sync DDEV State" and "Report issue" only Report issue is working.

### Additional context

de.php_perfect.intellij.ddev.cmd.CommandFailedException: Command timed out after 8 seconds: /usr/local/bin/ddev describe --json-output in /Users/bs/workspace/w3root/shopotralla
	at de.php_perfect.intellij.ddev.cmd.DdevImpl.execute(DdevImpl.java:33)
	at de.php_perfect.intellij.ddev.cmd.DdevImpl.describe(DdevImpl.java:22)
	at de.php_perfect.intellij.ddev.state.DdevStateManagerImpl.checkDescription(DdevStateManagerImpl.java:155)
	at de.php_perfect.intellij.ddev.state.DdevStateManagerImpl.lambda$updateConfiguration$1(DdevStateManagerImpl.java:67)
	at de.php_perfect.intellij.ddev.state.DdevStateManagerImpl.checkChanged(DdevStateManagerImpl.java:90)
	at de.php_perfect.intellij.ddev.state.DdevStateManagerImpl.updateConfiguration(DdevStateManagerImpl.java:65)
	at de.php_perfect.intellij.ddev.state.StateWatcherImpl.lambda$startWatching$0(StateWatcherImpl.java:33)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:275)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by nico-loeber** [comment] 2023-07-26 10:08
Hi @BenediktS1,

Your issue is a duplicate of https://github.com/php-perfect/ddev-intellij-plugin/issues/83 so I will close this one.
If you encounter such an exception as you posted, PHPStorm will offer to report it to the plugin author. 
This will give me additional information about your setup that might help to find out what is going wrong.
Please try to report the error and paste the Report ID in the linked issue (So I can give you feedback).

Thanks in advnce!

**Closed by nico-loeber** 2023-07-26 10:08 UTC
Labels: bug
