### ISSUE TITLE
Getting NoClassDefFoundError / PhpRemoteSdkAdditionalData error

### ISSUE THREAD

**Issue by njt1982** [php-perfect/ddev-intellij-plugin#36] opened 2022-05-09 09:12 UTC
Hi - I installed this via the alpha channel.

OSX 12.3.1 / PHPStorm 2022.1

```
java.lang.NoClassDefFoundError: com/jetbrains/php/remote/interpreter/PhpRemoteSdkAdditionalData
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
	at java.base/java.lang.Class.getDeclaredConstructors(Class.java:2357)
	at com.intellij.serviceContainer.ConstructorInjectionKt.getSortedMatchingConstructors(constructorInjection.kt:194)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:27)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:891)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:51)
	at com.intellij.serviceContainer.ServiceComponentAdapter.access$createAndInitialize(ServiceComponentAdapter.kt:12)
	at com.intellij.serviceContainer.ServiceComponentAdapter$doCreateInstance$1.compute(ServiceComponentAdapter.kt:45)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:238)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:44)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:119)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:73)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:66)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:610)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:584)
	at com.intellij.openapi.client.ClientAwareComponentManager.getFromSelfOrCurrentSession(ClientAwareComponentManager.kt:37)
	at com.intellij.openapi.client.ClientAwareComponentManager.getService(ClientAwareComponentManager.kt:22)
	at de.php_perfect.intellij.ddev.php.PhpInterpreterProvider.getInstance(PhpInterpreterProvider.java:10)
	at de.php_perfect.intellij.ddev.php.ConfigurationProviderImpl.configure(ConfigurationProviderImpl.java:33)
	at de.php_perfect.intellij.ddev.php.AutoConfigurePhpInterpreterListener.onDescriptionChanged(AutoConfigurePhpInterpreterListener.java:22)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeMethod(MessageBusImpl.java:642)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:617)
	at com.intellij.util.messages.impl.MessageBusImpl.deliverMessage(MessageBusImpl.java:417)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:391)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:373)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:34)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:180)
	at com.sun.proxy.$Proxy171.onDescriptionChanged(Unknown Source)
	at de.php_perfect.intellij.ddev.state.DdevStateManagerImpl.checkChanged(DdevStateManagerImpl.java:85)
	at de.php_perfect.intellij.ddev.state.DdevStateManagerImpl.initialize(DdevStateManagerImpl.java:33)
	at de.php_perfect.intellij.ddev.InitPluginActivity.runActivity(InitPluginActivity.java:15)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runStartupActivity(StartupManagerImpl.kt:311)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration(StartupManagerImpl.kt:290)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration$default(StartupManagerImpl.kt:285)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$1$1.run(StartupManagerImpl.kt:238)
	at com.intellij.openapi.project.DumbServiceImpl.runWithWaitForSmartModeDisabled(DumbServiceImpl.java:648)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$1.accept(StartupManagerImpl.kt:237)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$1.accept(StartupManagerImpl.kt:62)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processWithPluginDescriptor(ExtensionPointImpl.java:301)
	at com.intellij.openapi.extensions.ExtensionPointName.processWithPluginDescriptor(ExtensionPointName.java:143)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.kt:232)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runPostStartupActivities(StartupManagerImpl.kt:62)
	at com.intellij.ide.startup.impl.StartupManagerImpl$projectOpened$3$1.run(StartupManagerImpl.kt:180)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:365)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:343)
	at com.intellij.ide.startup.impl.StartupManagerImpl$projectOpened$3.run(StartupManagerImpl.kt:180)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.ClassNotFoundException: com.jetbrains.php.remote.interpreter.PhpRemoteSdkAdditionalData PluginClassLoader(plugin=PluginDescriptor(name=DDEV Integration, id=de.php_perfect.intellij.ddev, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/PhpStorm2022.1/plugins/ddev-intellij-plugin, version=1.0.0-alpha2, package=null, isBundled=false), packagePrefix=null, instanceId=98, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:215)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 62 more
```

Using ddev for Drupal projects.

I saw #25  - Looks like PHP Docker (along with the PHP remote sdk thing) wasn't enabled for me either, however I didn't get the "nice" error warning. Do you need to catch another class error?

**Comment by nico-loeber** [comment] 2022-05-09 16:05
Hi @njt1982,
Thanks for reporting this! It looks indeed like #25 and yes, I might need to be more defensive to avoid such an error, as I ineed only check for the docker plugin, as it has sub dependencies to the others.

But first, I want you to confirm the version of the plugin you have installed.

I got the the positive review reply from JetBrains at 11:13 AM and you have opend this issue at 11:12 AM, so I guess the new version wasn't available in the alpha channel when you installed it. ;)

You should find the plugin version here: 

File | Settings | Plugins

![image](https://user-images.githubusercontent.com/18308418/167450613-9eb50f9f-2f86-428f-80a2-eae834e796d3.png)

fyi, when a plugin is released, it has to go through a review process by jetbrains. Therefore, new versions will be available in the alpha channel and the marketplace one to two days later than they are actually published.

**Comment by nico-loeber** [comment] 2022-05-14 14:25
Closing this a I can not reproduce this since alpha3 and I don't get any feedback from @njt1982.

**Comment by njt1982** [comment] 2022-05-14 21:57
Sorry I didn’t see a reply.

it is working for me now, however I think the issue was a missing/not enabled plugin.

Do you not get the same error if you disable the remote PHP plugin?

(I would have thought if it was a required dependency it should have automatically been enabled?)

**Comment by nico-loeber** [comment] 2022-05-14 22:53
> Do you not get the same error if you disable the remote PHP plugin?

First of all: Sorry, I disabled the wrong plugin that also had "Remote" in name, stupid mistake on my side. I can now reproduce the error and will add a check for that as well of course!

> (I would have thought if it was a required dependency it should have automatically been enabled?)

The problem is, that these plugins are optional dependencies, because otherwise you could not use the plugin for WebStorm which does not offer PHP Support and so there won't be a remote PHP plugin.
IF PHP Support is available 3 more Plugins are required, namely PHP Remote Interpreter, PHP Docker and Docker. All those 3 plugins are bundled with PHPStorm so they are always installed but some people seem to deactivate them.

**Closed** 2022-05-18 20:36 UTC
Labels: bug
