### ISSUE TITLE
DDEV connection failed

### ISSUE THREAD

**Issue by CipixDevelopers** [php-perfect/ddev-intellij-plugin#114] opened 2022-10-14 08:12 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you sure that this bug is related to this DDEV Integration Plugin?

- [X] I am sure

### Enter your error report ID (If available)

d1c0741199b548348e7abe5aa23bfde3
4c181c2d75864c9dbcf503da54ece37a
6a9d0b82f8214d66922c31c2c1095b99

### Describe the bug

Trying to run a drush cex -y inside ddev container and it gives me these messages.

<img width="369" alt="Screenshot 2022-10-14 at 10 05 14" src="https://user-images.githubusercontent.com/75833745/195795814-0324a823-a3ab-43a9-9146-09425fb8de22.png">

I am running a lot of programs, it might be the lack of RAM, but it it seems to also happen when I'm only running PHPStorm.

Possibly related to https://github.com/php-perfect/ddev-intellij-plugin/issues/83
I am running ddev v1.21.2

### Steps to reproduce

By using the integration I randomly get connections failed. 
In this instance I was running a command (drush cex -y) in side the ddev web container.

**Noteworthy**: I do use this command frequently to switch between projects and turn ddev off
`ddev poweroff; brew update; brew upgrade; ddev delete images -y;`

**Comment by rfay** [comment] 2022-10-14 11:23
Please make sure you're using ddev v1.22.2+, as it has a significant improvement in how it decides whether there is internet available.

**Comment by CipixDevelopers** [comment] 2022-10-14 12:53
https://github.com/drud/ddev/releases

Version [v1.21.2](https://github.com/drud/ddev/releases/tag/v1.21.2) is the latest release. I assume v1.22.2 is in some other brew tap?

**Comment by rfay** [comment] 2022-10-14 12:56
Updated my comment. I just can't keep my ones and twos sorted out.  v1.22.2 is what you should be using here.

**Comment by CipixDevelopers** [comment] 2022-10-14 13:03
You mentioned v1.22.2 again, but it is not released in this repo https://github.com/drud/ddev/releases, I am on the latest v1.21.2.
Do I need to change my homebrew tap to a different one to join like a beta-channel?

**Comment by rfay** [comment] 2022-10-14 13:08
I *really* can't type it right. As I said I updated my comment, look at it as I apparently can't type. https://github.com/php-perfect/ddev-intellij-plugin/issues/114#issuecomment-1278876187

**Comment by CipixDevelopers** [comment] 2022-10-14 13:11
I noticed you changed it here https://github.com/php-perfect/ddev-intellij-plugin/issues/114#issuecomment-1278876187

But you mentioned v1.22.2 again after that "**v1.22.2 is what you should be using here.**" here: https://github.com/php-perfect/ddev-intellij-plugin/issues/114#issuecomment-1278972726

Which confuses me because v1.22.2 isn't released as far as I can see.

**Comment by mejta** [comment] 2022-10-15 12:05
@rfay Same issue here :( I'm using:

```
ddev version
 ITEM             VALUE
 DDEV version     v1.21.2
 architecture     arm64
 db               drud/ddev-dbserver-mariadb-10.4:v1.21.2
 dba              phpmyadmin:5
 ddev-ssh-agent   drud/ddev-ssh-agent:v1.21.2
 docker           20.10.17
 docker-compose   v2.10.2
 docker-platform  docker-desktop
 mutagen          0.16.0-rc1
 os               darwin
 router           drud/ddev-router:v1.21.2
 web              drud/ddev-webserver:v1.21.2
```

That happened when I switched from ddev on Colima to ddev on docker-desktop. I uninstalled ddev and Colima and made a fresh install of docker-desktop and ddev again.

It's a great tool, this integration and it would be great to make it work again :) 

Thank you!

Dan

**Comment by rfay** [comment] 2022-10-15 12:32
If you can get the plugin to make a report it may help the plugin authors to debug this. Thanks!

**Comment by nico-loeber** [comment] 2022-10-15 20:43
Hey @CipixDevelopers,

Thanks for reporting your issue.
I've checked the error reports you have linked. Two of them seem Docker related and one ddev releated.
See the stderr of the following commands.

```
Command '/usr/local/bin/ddev describe --json-output' returned non zero exit code {exitCode=1, timeout=false, cancelled=false, stdout=, stderr=[31mCould not connect to a docker provider. Please start or install a docker provider. For install help go to: https://ddev.readthedocs.io/en/latest/users/install/[0m}
```

```
Command '/usr/local/bin/ddev describe --json-output' returned non zero exit code {exitCode=1, timeout=false, cancelled=false, stdout=, stderr={"level":"fatal","msg":"\u001b[31mFailed to describe project(s): API error (502): Bad response from Docker engine\n\u001b[0m","time":"2022-10-14T10:15:53+02:00"}}
```

```
Command '/usr/local/bin/ddev describe --json-output' returned non zero exit code {exitCode=1, timeout=false, cancelled=false, stdout=, stderr=[31mFailed to open /Users/****/.ddev/.global_commands/.git/HEAD: open /Users/****/.ddev/.global_commands/.git/HEAD: no such file or directory[0m
}
```

I hope it's okay to say that you are using DDEV v1.21.2 on Docker Desktop on Mac OS X 12.6.1. This information might help @rfay to give some useful input.

As these errors are not directly related to the plugin I am not sure how I can help you here. :(
@rfay, any ideas?

**Comment by rfay** [comment] 2022-10-15 20:53
The first two are just broken Docker, as you say.

The third one shows "Failed to open /Users/****/.ddev/.global_commands/.git/HEAD". I'm not sure due to the editing whether that's the project .global_commands directory or a never-would-exist ~/.ddev/.global_commands directory. But if it's the project .ddev/.global_commands directory, please delete it (it's just created on `ddev start` anyway. And please take a look at your ~/.ddev/commands directory. Is it checked in via git? Is that intentional? Is git broken there? 

So:

1. See if `ddev describe` works in the project that failed.
2. Delete the project .ddev/.global_commands directory, `rm -r .ddev/.global_commands`. Make sure it's completely deleted.
3. See if git is broken in your (apparently) checked in ~/.ddev/commands directory.

**Comment by nico-loeber** [comment] 2022-10-15 20:58
@rfay the anonymized part of the path is `/{Name}/local projects/{projectName}/`. I did not want to disclose any private data.

Thanks for your support on this @rfay!

**Comment by CipixDevelopers** [comment] 2022-10-19 10:21
So we have a git instance in ~/.ddev/commands, here we have a bunch of (shared) custom commands that automatically get added to every project since in the {project}/.ddev/.global_commands folder. Maybe the fact that a git repo is running in ~/.ddev/commands is causing some unintended issues?

**Comment by rfay** [comment] 2022-10-19 12:36
Again, see if you can recreate any issue with `ddev describe`, as that's what the plugin is doing. But note above that 2 out of the 3 captured errors were about docker problems, so try to fix that too.

**Comment by jonaseberle** [comment] 2022-11-24 12:32
I don't know if I should open a new issue because there seem to be various problems tackled already in here.

Anyways, the failed Data Source connection was in my case that I was using 
```
database:
  type: mariadb
  version: "10.5"
```
yet the plugin generates a `:mysql:` connection string:
![image](https://user-images.githubusercontent.com/1678001/203784263-4f261fb2-49c7-4186-a811-763ed80f722e.png)

Somehow newer JDBC drivers seem to distinguish mariadb/mysql? 

Changing the connection URL `jdbc:mariadb://127.0.0.1:59002/db?user=db&password=db` fixes it in my case.

**Comment by nico-loeber** [comment] 2022-11-29 16:28
Hi @jonaseberle,

Are you using the latest version of the plugin?

This should be fixed in
- https://github.com/php-perfect/ddev-intellij-plugin/issues/115

**Comment by jonaseberle** [comment] 2022-11-29 19:38
@nico-loeber, I am using [v1.0.3](https://github.com/php-perfect/ddev-intellij-plugin/releases/tag/1.0.3)
Yes, thank you! https://github.com/php-perfect/ddev-intellij-plugin/issues/115 is exactly my issue.

**Comment by nico-loeber** [comment] 2022-12-04 23:42
@jonaseberle, I can not reproduce the wrong the database issue in the latest version (1.0.3). Maybe you have a datasource generated by an older version of the plugin? You can manually remove it and it will be regenerated after restart of your IDE or if you restart your ddev container.
If the data source is still generated wrong, please let me know in #115, thanks!

**Closed** 2023-07-30 09:26 UTC
Labels: bug
